//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAF.TextAnalytics.TextAnalyticsServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultTextAnalytics", Namespace="http://schemas.datacontract.org/2004/07/MAF.WCFTextAnalyticsService")]
    [System.SerializableAttribute()]
    public partial class FaultTextAnalytics : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorText {
            get {
                return this.ErrorTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorTextField, value) != true)) {
                    this.ErrorTextField = value;
                    this.RaisePropertyChanged("ErrorText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TextAnalyticsServiceReference.ITextAnalyticsService")]
    public interface ITextAnalyticsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAnalyticsService/SignIn", ReplyAction="http://tempuri.org/ITextAnalyticsService/SignInResponse")]
        string SignIn(string pLoginName, string pPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAnalyticsService/SignIn", ReplyAction="http://tempuri.org/ITextAnalyticsService/SignInResponse")]
        System.Threading.Tasks.Task<string> SignInAsync(string pLoginName, string pPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAnalyticsService/LogOut", ReplyAction="http://tempuri.org/ITextAnalyticsService/LogOutResponse")]
        void LogOut(string pUserToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAnalyticsService/LogOut", ReplyAction="http://tempuri.org/ITextAnalyticsService/LogOutResponse")]
        System.Threading.Tasks.Task LogOutAsync(string pUserToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAnalyticsService/SignUp", ReplyAction="http://tempuri.org/ITextAnalyticsService/SignUpResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MAF.TextAnalytics.TextAnalyticsServiceReference.FaultTextAnalytics), Action="http://tempuri.org/ITextAnalyticsService/SignUpFaultTextAnalyticsFault", Name="FaultTextAnalytics", Namespace="http://schemas.datacontract.org/2004/07/MAF.WCFTextAnalyticsService")]
        void SignUp(string pLoginName, string pUserName, string pPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAnalyticsService/SignUp", ReplyAction="http://tempuri.org/ITextAnalyticsService/SignUpResponse")]
        System.Threading.Tasks.Task SignUpAsync(string pLoginName, string pUserName, string pPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAnalyticsService/GetStatus", ReplyAction="http://tempuri.org/ITextAnalyticsService/GetStatusResponse")]
        bool GetStatus(string pToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAnalyticsService/GetStatus", ReplyAction="http://tempuri.org/ITextAnalyticsService/GetStatusResponse")]
        System.Threading.Tasks.Task<bool> GetStatusAsync(string pToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAnalyticsService/SourceFileExist", ReplyAction="http://tempuri.org/ITextAnalyticsService/SourceFileExistResponse")]
        bool SourceFileExist(string pSourceFileMD5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAnalyticsService/SourceFileExist", ReplyAction="http://tempuri.org/ITextAnalyticsService/SourceFileExistResponse")]
        System.Threading.Tasks.Task<bool> SourceFileExistAsync(string pSourceFileMD5);
        
        // CODEGEN: Generating message contract since the wrapper name (FileDownloadMessage) of message FileDownloadMessage does not match the default value (GetResultFile)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAnalyticsService/GetResultFile", ReplyAction="http://tempuri.org/ITextAnalyticsService/GetResultFileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MAF.TextAnalytics.TextAnalyticsServiceReference.FaultTextAnalytics), Action="http://tempuri.org/ITextAnalyticsService/GetResultFileFaultTextAnalyticsFault", Name="FaultTextAnalytics", Namespace="http://schemas.datacontract.org/2004/07/MAF.WCFTextAnalyticsService")]
        MAF.TextAnalytics.TextAnalyticsServiceReference.FileDownloadReturnMessage GetResultFile(MAF.TextAnalytics.TextAnalyticsServiceReference.FileDownloadMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAnalyticsService/GetResultFile", ReplyAction="http://tempuri.org/ITextAnalyticsService/GetResultFileResponse")]
        System.Threading.Tasks.Task<MAF.TextAnalytics.TextAnalyticsServiceReference.FileDownloadReturnMessage> GetResultFileAsync(MAF.TextAnalytics.TextAnalyticsServiceReference.FileDownloadMessage request);
        
        // CODEGEN: Generating message contract since the wrapper name (FileUploadMessage) of message FileUploadMessage does not match the default value (RunCalculation)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAnalyticsService/RunCalculation", ReplyAction="http://tempuri.org/ITextAnalyticsService/RunCalculationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MAF.TextAnalytics.TextAnalyticsServiceReference.FaultTextAnalytics), Action="http://tempuri.org/ITextAnalyticsService/RunCalculationFaultTextAnalyticsFault", Name="FaultTextAnalytics", Namespace="http://schemas.datacontract.org/2004/07/MAF.WCFTextAnalyticsService")]
        MAF.TextAnalytics.TextAnalyticsServiceReference.FileDownloadReturnMessage RunCalculation(MAF.TextAnalytics.TextAnalyticsServiceReference.FileUploadMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAnalyticsService/RunCalculation", ReplyAction="http://tempuri.org/ITextAnalyticsService/RunCalculationResponse")]
        System.Threading.Tasks.Task<MAF.TextAnalytics.TextAnalyticsServiceReference.FileDownloadReturnMessage> RunCalculationAsync(MAF.TextAnalytics.TextAnalyticsServiceReference.FileUploadMessage request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileDownloadMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileDownloadMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string MD5;
        
        public FileDownloadMessage() {
        }
        
        public FileDownloadMessage(string MD5) {
            this.MD5 = MD5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileDownloadReturnMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileDownloadReturnMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string DownloadedFilename;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public FileDownloadReturnMessage() {
        }
        
        public FileDownloadReturnMessage(string DownloadedFilename, System.IO.Stream FileByteStream) {
            this.DownloadedFilename = DownloadedFilename;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileUploadMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileUploadMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Filename;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string UserToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public FileUploadMessage() {
        }
        
        public FileUploadMessage(string Filename, string UserToken, System.IO.Stream FileByteStream) {
            this.Filename = Filename;
            this.UserToken = UserToken;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITextAnalyticsServiceChannel : MAF.TextAnalytics.TextAnalyticsServiceReference.ITextAnalyticsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TextAnalyticsServiceClient : System.ServiceModel.ClientBase<MAF.TextAnalytics.TextAnalyticsServiceReference.ITextAnalyticsService>, MAF.TextAnalytics.TextAnalyticsServiceReference.ITextAnalyticsService {
        
        public TextAnalyticsServiceClient() {
        }
        
        public TextAnalyticsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TextAnalyticsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextAnalyticsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextAnalyticsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SignIn(string pLoginName, string pPassword) {
            return base.Channel.SignIn(pLoginName, pPassword);
        }
        
        public System.Threading.Tasks.Task<string> SignInAsync(string pLoginName, string pPassword) {
            return base.Channel.SignInAsync(pLoginName, pPassword);
        }
        
        public void LogOut(string pUserToken) {
            base.Channel.LogOut(pUserToken);
        }
        
        public System.Threading.Tasks.Task LogOutAsync(string pUserToken) {
            return base.Channel.LogOutAsync(pUserToken);
        }
        
        public void SignUp(string pLoginName, string pUserName, string pPassword) {
            base.Channel.SignUp(pLoginName, pUserName, pPassword);
        }
        
        public System.Threading.Tasks.Task SignUpAsync(string pLoginName, string pUserName, string pPassword) {
            return base.Channel.SignUpAsync(pLoginName, pUserName, pPassword);
        }
        
        public bool GetStatus(string pToken) {
            return base.Channel.GetStatus(pToken);
        }
        
        public System.Threading.Tasks.Task<bool> GetStatusAsync(string pToken) {
            return base.Channel.GetStatusAsync(pToken);
        }
        
        public bool SourceFileExist(string pSourceFileMD5) {
            return base.Channel.SourceFileExist(pSourceFileMD5);
        }
        
        public System.Threading.Tasks.Task<bool> SourceFileExistAsync(string pSourceFileMD5) {
            return base.Channel.SourceFileExistAsync(pSourceFileMD5);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MAF.TextAnalytics.TextAnalyticsServiceReference.FileDownloadReturnMessage MAF.TextAnalytics.TextAnalyticsServiceReference.ITextAnalyticsService.GetResultFile(MAF.TextAnalytics.TextAnalyticsServiceReference.FileDownloadMessage request) {
            return base.Channel.GetResultFile(request);
        }
        
        public string GetResultFile(string MD5, out System.IO.Stream FileByteStream) {
            MAF.TextAnalytics.TextAnalyticsServiceReference.FileDownloadMessage inValue = new MAF.TextAnalytics.TextAnalyticsServiceReference.FileDownloadMessage();
            inValue.MD5 = MD5;
            MAF.TextAnalytics.TextAnalyticsServiceReference.FileDownloadReturnMessage retVal = ((MAF.TextAnalytics.TextAnalyticsServiceReference.ITextAnalyticsService)(this)).GetResultFile(inValue);
            FileByteStream = retVal.FileByteStream;
            return retVal.DownloadedFilename;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MAF.TextAnalytics.TextAnalyticsServiceReference.FileDownloadReturnMessage> MAF.TextAnalytics.TextAnalyticsServiceReference.ITextAnalyticsService.GetResultFileAsync(MAF.TextAnalytics.TextAnalyticsServiceReference.FileDownloadMessage request) {
            return base.Channel.GetResultFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<MAF.TextAnalytics.TextAnalyticsServiceReference.FileDownloadReturnMessage> GetResultFileAsync(string MD5) {
            MAF.TextAnalytics.TextAnalyticsServiceReference.FileDownloadMessage inValue = new MAF.TextAnalytics.TextAnalyticsServiceReference.FileDownloadMessage();
            inValue.MD5 = MD5;
            return ((MAF.TextAnalytics.TextAnalyticsServiceReference.ITextAnalyticsService)(this)).GetResultFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MAF.TextAnalytics.TextAnalyticsServiceReference.FileDownloadReturnMessage MAF.TextAnalytics.TextAnalyticsServiceReference.ITextAnalyticsService.RunCalculation(MAF.TextAnalytics.TextAnalyticsServiceReference.FileUploadMessage request) {
            return base.Channel.RunCalculation(request);
        }
        
        public string RunCalculation(string Filename, string UserToken, ref System.IO.Stream FileByteStream) {
            MAF.TextAnalytics.TextAnalyticsServiceReference.FileUploadMessage inValue = new MAF.TextAnalytics.TextAnalyticsServiceReference.FileUploadMessage();
            inValue.Filename = Filename;
            inValue.UserToken = UserToken;
            inValue.FileByteStream = FileByteStream;
            MAF.TextAnalytics.TextAnalyticsServiceReference.FileDownloadReturnMessage retVal = ((MAF.TextAnalytics.TextAnalyticsServiceReference.ITextAnalyticsService)(this)).RunCalculation(inValue);
            FileByteStream = retVal.FileByteStream;
            return retVal.DownloadedFilename;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MAF.TextAnalytics.TextAnalyticsServiceReference.FileDownloadReturnMessage> MAF.TextAnalytics.TextAnalyticsServiceReference.ITextAnalyticsService.RunCalculationAsync(MAF.TextAnalytics.TextAnalyticsServiceReference.FileUploadMessage request) {
            return base.Channel.RunCalculationAsync(request);
        }
        
        public System.Threading.Tasks.Task<MAF.TextAnalytics.TextAnalyticsServiceReference.FileDownloadReturnMessage> RunCalculationAsync(string Filename, string UserToken, System.IO.Stream FileByteStream) {
            MAF.TextAnalytics.TextAnalyticsServiceReference.FileUploadMessage inValue = new MAF.TextAnalytics.TextAnalyticsServiceReference.FileUploadMessage();
            inValue.Filename = Filename;
            inValue.UserToken = UserToken;
            inValue.FileByteStream = FileByteStream;
            return ((MAF.TextAnalytics.TextAnalyticsServiceReference.ITextAnalyticsService)(this)).RunCalculationAsync(inValue);
        }
    }
}
